In [5]:
import os

if os.getcwd().endswith("test"):
    os.chdir("..")

print(os.getcwd())

c:\Users\ylu174\my_file\research\bilipschitz_scalars_EML\bilipschitz_experiment\ScalarEMLP


In [6]:
import experiments.trainer.hamiltonian_dynamics as hd
import torch
print(dir(hd))
hd.unpack(torch.tensor([1.0, 2.0, 3.0, 4.0]))

['Animation', 'Axes3D', 'BHamiltonianFlow', 'BOdeFlow', 'Classifier', 'CoupledPendulumAnimation', 'Dataset', 'DkeR3', 'DoubleSpringPendulum', 'HamiltonianDataset', 'HamiltonianFlow', 'IntegratedDynamicsTrainer', 'IntegratedODETrainer', 'Iterable', 'O2eR3', 'PendulumAnimation', 'Regressor', 'SHO', 'SO2eR3', 'Scalar', 'T', 'Trivial', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'align2ref', 'animation', 'export', 'flatten_dict', 'grad', 'hamiltonian_dynamics', 'helix', 'hnnScalars_trial', 'hnn_trial', 'jacfwd', 'jax', 'jit', 'jnp', 'jvp', 'log_rollout_error', 'log_rollout_error_ode', 'np', 'objax', 'odeScalars_trial', 'ode_trial', 'odeint', 'os', 'pack', 'partial', 'plt', 'pred_and_gt', 'pred_and_gt_ode', 'random', 'rel_err', 'symplectic_form', 'torch', 'types', 'unpack', 'vjp', 'vmap']


(tensor([1., 2.]), tensor([3., 4.]))

In [7]:
from experiments.trainer.hamiltonian_dynamics import *
import torch
import jax.numpy as jnp

z=torch.rand(24).reshape(3, 4, 2)
z1,z2=unpack(z)
# print(z)
# print("Unpacked tensor:", unpack(z))

z1=torch.rand(24).reshape(3,4,2)
z2=torch.rand(12).reshape(3,4,1)

a1,a2=jnp.array(z1), jnp.array(z2)

# print("packed tensor:", pack(a1,a2))

print(symplectic_form(jnp.array(z)))

[[[ 0.60940737 -0.60392976]
  [ 0.5885999  -0.2780819 ]
  [ 0.8775891  -0.00413549]
  [ 0.17612326 -0.8701343 ]]

 [[ 0.2648673  -0.14541495]
  [ 0.72792983 -0.32285058]
  [ 0.88184583 -0.34673917]
  [ 0.2576151  -0.08129281]]

 [[ 0.19667208 -0.6303047 ]
  [ 0.6264532  -0.8530836 ]
  [ 0.8070553  -0.95485055]
  [ 0.7479155  -0.9511088 ]]]


In [8]:
import numpy as np
np.random.randn(100,6)

array([[ 3.30841484e-01, -4.74369193e-01,  1.36794701e+00,
         1.56444008e+00, -3.21189155e-01,  7.48930435e-01],
       [-3.33353617e-01, -1.14799278e+00, -5.31846406e-01,
        -9.63122101e-01, -1.83265414e+00,  6.44313571e-04],
       [ 1.35965544e+00, -6.86407691e-02, -2.66287421e-01,
         1.39176596e-01, -5.82082345e-02, -4.73098143e-01],
       [-6.17687063e-01, -1.68210870e+00,  5.82817907e-01,
        -5.73588600e-01, -1.15947472e-02, -1.90911242e-01],
       [-2.84579565e-01,  8.61271600e-01, -5.56765818e-01,
         3.56483493e-01,  1.25602545e+00, -3.59368210e-01],
       [ 1.58246565e+00,  4.21531524e-01, -6.73968101e-01,
        -9.00366907e-01, -1.52306197e+00,  5.38888272e-02],
       [ 1.06565300e-01,  1.03776374e+00, -1.90100029e-01,
        -3.06658988e-01, -3.91352283e-03, -5.85783967e-01],
       [-7.95854762e-02, -1.35334292e+00, -6.27320524e-01,
        -1.41602556e-01, -4.87128337e-01,  2.07575768e+00],
       [-7.25218004e-01, -1.43254727e+00,  1.767

## Hamiltonian computation